POST http://localhost:3000/users
Content-type: application/json

{
  "name": "Howie",
  "email": "howie@email.com",
  "password": "password"
}

###
PATCH http://localhost:3000/users
Content-type: application/json

{
  "id": 3,
  "group_id": 1
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "ben@email.com",
  "password": "password"
}

###
POST http://localhost:3000/groups.json
Content-type: application/json

{
  "name": "Snyder"
}