POST http://localhost:3000/users
Content-type: application/json

{
  "name": "Ben",
  "email": "ben@email.com",
  "password": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "ben@email.com",
  "password": "password"
}