@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjkwNjU4NTF9.jtqxUlkYgG2tOj25xfajMW40SSUw2PWRQsmenqveIaM

GET http://localhost:3000/users/1
Authorization: Bearer {{jwt}}

###
POST http://localhost:3000/users
Content-type: application/json

{
  "name": "Howie",
  "email": "howie@email.com",
  "password": "password",
  "group_id": 1
}

###
PATCH http://localhost:3000/users
Content-type: application/json

{
  "id": 3,
  "group_id": 1
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "ben@email.com",
  "password": "password"
}

###
GET http://localhost:3000/groups/1
Authorization: Bearer {{jwt}}

###
POST http://localhost:3000/groups.json
Content-type: application/json

{
  "name": "Snyder"
}

###
POST http://localhost:3000/bets.json
Authorization: Bearer {{jwt}}
Content-type: application/json

{
  "title": "Basketball",
  "description": "First to 10",
  "wager_object": "Beer",
  "wager_amount": 4
}